// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package api_model

import "ramos.com/go-gin-pulsar-api/pkg/model"

// Error defines model for error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// IngestResponse defines model for ingestResponse.
type IngestResponse struct {
	Received bool `json:"received"`
}

// IngestDataJSONRequestBody defines body for IngestData for application/json ContentType.
type IngestDataJSONRequestBody = model.IngestionRequest
