apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: go-gin-pulsar-api
  labels:
    app: go-gin-pulsar-api
spec:
  serviceName: "go-gin-pulsar-api"
  selector:
    matchLabels:
      app: go-gin-pulsar-api
  replicas: 22
  template:
    metadata:
      labels:
        app: go-gin-pulsar-api
      annotations:
        prometheus.io/port: "8001"
        prometheus.io/scrape: "true"        
    spec:
      containers:
        - name: go-gin-pulsar-api
          image: go-gin-pulsar-api:0.0.1
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 2
              memory: 8Gi
            limits:
              cpu: 12
              memory: 24Gi
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 45
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 45
            periodSeconds: 10
          env:
          - name: ENV
            value: "prod"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: go-gin-pulsar-api-svc
spec:
  selector:
    app: go-gin-pulsar-api
  type: ClusterIP
  ports:
    - name: service
      targetPort: 8000
      port: 8000
    - name: metrics
      port: 8001
      protocol: TCP
      targetPort: 8001